! =============================================================================
! FRR Configuration - DS_B2 (Distribution Switch B2)
! Router ID: 4.4.4.2
! OSPF Area 20 — Block B (Backup)
! =============================================================================

frr version 8.5
frr defaults traditional
hostname DS_B2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface db2-peer
 ip address 172.16.2.2/30
 ip ospf network point-to-point
 ip ospf area 0.0.0.20
 ip ospf cost 10
!
interface db2-cs1
 ip address 172.16.2.14/30
 ip ospf network point-to-point
 ip ospf area 0.0.0.20
 ip ospf cost 20
!
interface db2-cs2
 ip address 172.16.2.18/30
 ip ospf network point-to-point
 ip ospf area 0.0.0.20
 ip ospf cost 30
!
interface vlan20
 ip address 10.1.7.253/22
!
interface vlan30
 ip address 10.1.11.253/22
!
interface vlan120
 ip address 10.2.1.253/24
!

router ospf
 ospf router-id 4.4.4.2
 redistribute connected
 network 172.16.2.0/30 area 0.0.0.20
 network 172.16.2.12/30 area 0.0.0.20
 network 172.16.2.16/30 area 0.0.0.20
 network 10.1.4.0/22 area 0.0.0.20
 network 10.1.8.0/22 area 0.0.0.20
 network 10.2.1.0/24 area 0.0.0.20
 passive-interface vlan20
 passive-interface vlan30
 passive-interface vlan120
!

line vty
!
